// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POSSolution.Application.Context;

namespace POSSolution.Application.Migrations
{
    [DbContext(typeof(POSContext))]
    [Migration("20200222140406_AddShopStatus")]
    partial class AddShopStatus
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("POSSolution.Application.Models.Region", b =>
                {
                    b.Property<Guid>("regionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("shopId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("regionId");

                    b.HasIndex("shopId");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("POSSolution.Application.Models.Shop", b =>
                {
                    b.Property<Guid>("shopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("createUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("shopId");

                    b.ToTable("Shops");
                });

            modelBuilder.Entity("POSSolution.Application.Models.ShopStatus", b =>
                {
                    b.Property<Guid>("statusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("statusName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("statusId");

                    b.ToTable("ShopStatuses");
                });

            modelBuilder.Entity("POSSolution.Application.Models.Region", b =>
                {
                    b.HasOne("POSSolution.Application.Models.Shop", "shop")
                        .WithMany("regions")
                        .HasForeignKey("shopId");
                });
#pragma warning restore 612, 618
        }
    }
}
